### ISSUE TITLE
enable_forwarding.sh

### ISSUE THREAD

**Issue by chamilad** [eranyanay/cni-from-scratch#1]
Thanks for the great presentation! I watched on youtube and there was a step that I couldn't understand. Could you please add the contents of  `enable_forwarding.sh`?

Is it enabling portforwarding in the kernel like the following?

```
echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
```

https://www.digitalocean.com/community/tutorials/how-to-forward-ports-through-a-linux-gateway-with-iptables

**Comment by eranyanay** [comment]
@chamilad Take a look at [init.sh](https://github.com/eranyanay/cni-from-scratch/blob/master/init.sh), which contains all the required changes
Forwarding for pod to pod communication is the first step in that file:
```
iptables -A FORWARD -s 10.240.0.0/16 -j ACCEPT
iptables -A FORWARD -d 10.240.0.0/16 -j ACCEPT
```

**Comment by chamilad** [comment]
Thanks! Understood.
